// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/telemetry.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Envelope struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	SessionId   string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Sequence    uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	TimestampNs uint64                 `protobuf:"varint,3,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	Pid         uint32                 `protobuf:"varint,4,opt,name=pid,proto3" json:"pid,omitempty"`
	Tid         uint32                 `protobuf:"varint,5,opt,name=tid,proto3" json:"tid,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*Envelope_ProcessInfo
	//	*Envelope_ClientHello
	//	*Envelope_Code
	//	*Envelope_KernelLaunch
	//	*Envelope_Stats
	Event         isEnvelope_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_proto_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Envelope) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Envelope) GetTimestampNs() uint64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *Envelope) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Envelope) GetTid() uint32 {
	if x != nil {
		return x.Tid
	}
	return 0
}

func (x *Envelope) GetEvent() isEnvelope_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *Envelope) GetProcessInfo() *ProcessInfoEvent {
	if x != nil {
		if x, ok := x.Event.(*Envelope_ProcessInfo); ok {
			return x.ProcessInfo
		}
	}
	return nil
}

func (x *Envelope) GetClientHello() *ClientHello {
	if x != nil {
		if x, ok := x.Event.(*Envelope_ClientHello); ok {
			return x.ClientHello
		}
	}
	return nil
}

func (x *Envelope) GetCode() *CodeEvent {
	if x != nil {
		if x, ok := x.Event.(*Envelope_Code); ok {
			return x.Code
		}
	}
	return nil
}

func (x *Envelope) GetKernelLaunch() *KernelLaunchEvent {
	if x != nil {
		if x, ok := x.Event.(*Envelope_KernelLaunch); ok {
			return x.KernelLaunch
		}
	}
	return nil
}

func (x *Envelope) GetStats() *StatsEvent {
	if x != nil {
		if x, ok := x.Event.(*Envelope_Stats); ok {
			return x.Stats
		}
	}
	return nil
}

type isEnvelope_Event interface {
	isEnvelope_Event()
}

type Envelope_ProcessInfo struct {
	ProcessInfo *ProcessInfoEvent `protobuf:"bytes,10,opt,name=process_info,json=processInfo,proto3,oneof"`
}

type Envelope_ClientHello struct {
	ClientHello *ClientHello `protobuf:"bytes,11,opt,name=client_hello,json=clientHello,proto3,oneof"`
}

type Envelope_Code struct {
	Code *CodeEvent `protobuf:"bytes,12,opt,name=code,proto3,oneof"`
}

type Envelope_KernelLaunch struct {
	KernelLaunch *KernelLaunchEvent `protobuf:"bytes,13,opt,name=kernel_launch,json=kernelLaunch,proto3,oneof"`
}

type Envelope_Stats struct {
	Stats *StatsEvent `protobuf:"bytes,14,opt,name=stats,proto3,oneof"`
}

func (*Envelope_ProcessInfo) isEnvelope_Event() {}

func (*Envelope_ClientHello) isEnvelope_Event() {}

func (*Envelope_Code) isEnvelope_Event() {}

func (*Envelope_KernelLaunch) isEnvelope_Event() {}

func (*Envelope_Stats) isEnvelope_Event() {}

type ProcessInfoEvent struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Ppid               uint32                 `protobuf:"varint,1,opt,name=ppid,proto3" json:"ppid,omitempty"`
	Uid                uint32                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid                uint32                 `protobuf:"varint,3,opt,name=gid,proto3" json:"gid,omitempty"`
	Hostname           string                 `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	ExePath            string                 `protobuf:"bytes,5,opt,name=exe_path,json=exePath,proto3" json:"exe_path,omitempty"`
	Cwd                string                 `protobuf:"bytes,6,opt,name=cwd,proto3" json:"cwd,omitempty"`
	Argv               []string               `protobuf:"bytes,7,rep,name=argv,proto3" json:"argv,omitempty"`
	ProcessStartTimeNs uint64                 `protobuf:"varint,8,opt,name=process_start_time_ns,json=processStartTimeNs,proto3" json:"process_start_time_ns,omitempty"`
	HookVersion        string                 `protobuf:"bytes,9,opt,name=hook_version,json=hookVersion,proto3" json:"hook_version,omitempty"`
	ClientVersion      string                 `protobuf:"bytes,10,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProcessInfoEvent) Reset() {
	*x = ProcessInfoEvent{}
	mi := &file_proto_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfoEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfoEvent) ProtoMessage() {}

func (x *ProcessInfoEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfoEvent.ProtoReflect.Descriptor instead.
func (*ProcessInfoEvent) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessInfoEvent) GetPpid() uint32 {
	if x != nil {
		return x.Ppid
	}
	return 0
}

func (x *ProcessInfoEvent) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ProcessInfoEvent) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *ProcessInfoEvent) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ProcessInfoEvent) GetExePath() string {
	if x != nil {
		return x.ExePath
	}
	return ""
}

func (x *ProcessInfoEvent) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *ProcessInfoEvent) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

func (x *ProcessInfoEvent) GetProcessStartTimeNs() uint64 {
	if x != nil {
		return x.ProcessStartTimeNs
	}
	return 0
}

func (x *ProcessInfoEvent) GetHookVersion() string {
	if x != nil {
		return x.HookVersion
	}
	return ""
}

func (x *ProcessInfoEvent) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

type ClientHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Pid           uint32                 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientHello) Reset() {
	*x = ClientHello{}
	mi := &file_proto_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHello) ProtoMessage() {}

func (x *ClientHello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHello.ProtoReflect.Descriptor instead.
func (*ClientHello) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *ClientHello) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ClientHello) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type CodeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CodeId        uint32                 `protobuf:"varint,1,opt,name=code_id,json=codeId,proto3" json:"code_id,omitempty"`
	CodeType      uint32                 `protobuf:"varint,2,opt,name=code_type,json=codeType,proto3" json:"code_type,omitempty"`
	Sha256        []byte                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodeEvent) Reset() {
	*x = CodeEvent{}
	mi := &file_proto_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeEvent) ProtoMessage() {}

func (x *CodeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeEvent.ProtoReflect.Descriptor instead.
func (*CodeEvent) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *CodeEvent) GetCodeId() uint32 {
	if x != nil {
		return x.CodeId
	}
	return 0
}

func (x *CodeEvent) GetCodeType() uint32 {
	if x != nil {
		return x.CodeType
	}
	return 0
}

func (x *CodeEvent) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

func (x *CodeEvent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type KernelLaunchEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	KernelName     string                 `protobuf:"bytes,2,opt,name=kernel_name,json=kernelName,proto3" json:"kernel_name,omitempty"`
	CodeId         uint32                 `protobuf:"varint,3,opt,name=code_id,json=codeId,proto3" json:"code_id,omitempty"`
	GridDimX       uint32                 `protobuf:"varint,4,opt,name=grid_dim_x,json=gridDimX,proto3" json:"grid_dim_x,omitempty"`
	GridDimY       uint32                 `protobuf:"varint,5,opt,name=grid_dim_y,json=gridDimY,proto3" json:"grid_dim_y,omitempty"`
	GridDimZ       uint32                 `protobuf:"varint,6,opt,name=grid_dim_z,json=gridDimZ,proto3" json:"grid_dim_z,omitempty"`
	BlockDimX      uint32                 `protobuf:"varint,7,opt,name=block_dim_x,json=blockDimX,proto3" json:"block_dim_x,omitempty"`
	BlockDimY      uint32                 `protobuf:"varint,8,opt,name=block_dim_y,json=blockDimY,proto3" json:"block_dim_y,omitempty"`
	BlockDimZ      uint32                 `protobuf:"varint,9,opt,name=block_dim_z,json=blockDimZ,proto3" json:"block_dim_z,omitempty"`
	SharedMemBytes uint32                 `protobuf:"varint,10,opt,name=shared_mem_bytes,json=sharedMemBytes,proto3" json:"shared_mem_bytes,omitempty"`
	Stream         uint64                 `protobuf:"varint,11,opt,name=stream,proto3" json:"stream,omitempty"`
	DevicePciBusId string                 `protobuf:"bytes,12,opt,name=device_pci_bus_id,json=devicePciBusId,proto3" json:"device_pci_bus_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KernelLaunchEvent) Reset() {
	*x = KernelLaunchEvent{}
	mi := &file_proto_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KernelLaunchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KernelLaunchEvent) ProtoMessage() {}

func (x *KernelLaunchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KernelLaunchEvent.ProtoReflect.Descriptor instead.
func (*KernelLaunchEvent) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *KernelLaunchEvent) GetKernelName() string {
	if x != nil {
		return x.KernelName
	}
	return ""
}

func (x *KernelLaunchEvent) GetCodeId() uint32 {
	if x != nil {
		return x.CodeId
	}
	return 0
}

func (x *KernelLaunchEvent) GetGridDimX() uint32 {
	if x != nil {
		return x.GridDimX
	}
	return 0
}

func (x *KernelLaunchEvent) GetGridDimY() uint32 {
	if x != nil {
		return x.GridDimY
	}
	return 0
}

func (x *KernelLaunchEvent) GetGridDimZ() uint32 {
	if x != nil {
		return x.GridDimZ
	}
	return 0
}

func (x *KernelLaunchEvent) GetBlockDimX() uint32 {
	if x != nil {
		return x.BlockDimX
	}
	return 0
}

func (x *KernelLaunchEvent) GetBlockDimY() uint32 {
	if x != nil {
		return x.BlockDimY
	}
	return 0
}

func (x *KernelLaunchEvent) GetBlockDimZ() uint32 {
	if x != nil {
		return x.BlockDimZ
	}
	return 0
}

func (x *KernelLaunchEvent) GetSharedMemBytes() uint32 {
	if x != nil {
		return x.SharedMemBytes
	}
	return 0
}

func (x *KernelLaunchEvent) GetStream() uint64 {
	if x != nil {
		return x.Stream
	}
	return 0
}

func (x *KernelLaunchEvent) GetDevicePciBusId() string {
	if x != nil {
		return x.DevicePciBusId
	}
	return ""
}

type StatsEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DroppedEvents uint64                 `protobuf:"varint,1,opt,name=dropped_events,json=droppedEvents,proto3" json:"dropped_events,omitempty"`
	DroppedBytes  uint64                 `protobuf:"varint,2,opt,name=dropped_bytes,json=droppedBytes,proto3" json:"dropped_bytes,omitempty"`
	QueuedEvents  uint64                 `protobuf:"varint,3,opt,name=queued_events,json=queuedEvents,proto3" json:"queued_events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsEvent) Reset() {
	*x = StatsEvent{}
	mi := &file_proto_telemetry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsEvent) ProtoMessage() {}

func (x *StatsEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsEvent.ProtoReflect.Descriptor instead.
func (*StatsEvent) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{5}
}

func (x *StatsEvent) GetDroppedEvents() uint64 {
	if x != nil {
		return x.DroppedEvents
	}
	return 0
}

func (x *StatsEvent) GetDroppedBytes() uint64 {
	if x != nil {
		return x.DroppedBytes
	}
	return 0
}

func (x *StatsEvent) GetQueuedEvents() uint64 {
	if x != nil {
		return x.QueuedEvents
	}
	return 0
}

var File_proto_telemetry_proto protoreflect.FileDescriptor

const file_proto_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x15proto/telemetry.proto\x12\x16sassguard.telemetry.v1\"\xf5\x03\n" +
	"\bEnvelope\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12!\n" +
	"\ftimestamp_ns\x18\x03 \x01(\x04R\vtimestampNs\x12\x10\n" +
	"\x03pid\x18\x04 \x01(\rR\x03pid\x12\x10\n" +
	"\x03tid\x18\x05 \x01(\rR\x03tid\x12M\n" +
	"\fprocess_info\x18\n" +
	" \x01(\v2(.sassguard.telemetry.v1.ProcessInfoEventH\x00R\vprocessInfo\x12H\n" +
	"\fclient_hello\x18\v \x01(\v2#.sassguard.telemetry.v1.ClientHelloH\x00R\vclientHello\x127\n" +
	"\x04code\x18\f \x01(\v2!.sassguard.telemetry.v1.CodeEventH\x00R\x04code\x12P\n" +
	"\rkernel_launch\x18\r \x01(\v2).sassguard.telemetry.v1.KernelLaunchEventH\x00R\fkernelLaunch\x12:\n" +
	"\x05stats\x18\x0e \x01(\v2\".sassguard.telemetry.v1.StatsEventH\x00R\x05statsB\a\n" +
	"\x05event\"\xa4\x02\n" +
	"\x10ProcessInfoEvent\x12\x12\n" +
	"\x04ppid\x18\x01 \x01(\rR\x04ppid\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\x03 \x01(\rR\x03gid\x12\x1a\n" +
	"\bhostname\x18\x04 \x01(\tR\bhostname\x12\x19\n" +
	"\bexe_path\x18\x05 \x01(\tR\aexePath\x12\x10\n" +
	"\x03cwd\x18\x06 \x01(\tR\x03cwd\x12\x12\n" +
	"\x04argv\x18\a \x03(\tR\x04argv\x121\n" +
	"\x15process_start_time_ns\x18\b \x01(\x04R\x12processStartTimeNs\x12!\n" +
	"\fhook_version\x18\t \x01(\tR\vhookVersion\x12%\n" +
	"\x0eclient_version\x18\n" +
	" \x01(\tR\rclientVersion\">\n" +
	"\vClientHello\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\rR\x03pid\"m\n" +
	"\tCodeEvent\x12\x17\n" +
	"\acode_id\x18\x01 \x01(\rR\x06codeId\x12\x1b\n" +
	"\tcode_type\x18\x02 \x01(\rR\bcodeType\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\fR\x06sha256\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"\xf4\x02\n" +
	"\x11KernelLaunchEvent\x12\x1f\n" +
	"\vkernel_name\x18\x02 \x01(\tR\n" +
	"kernelName\x12\x17\n" +
	"\acode_id\x18\x03 \x01(\rR\x06codeId\x12\x1c\n" +
	"\n" +
	"grid_dim_x\x18\x04 \x01(\rR\bgridDimX\x12\x1c\n" +
	"\n" +
	"grid_dim_y\x18\x05 \x01(\rR\bgridDimY\x12\x1c\n" +
	"\n" +
	"grid_dim_z\x18\x06 \x01(\rR\bgridDimZ\x12\x1e\n" +
	"\vblock_dim_x\x18\a \x01(\rR\tblockDimX\x12\x1e\n" +
	"\vblock_dim_y\x18\b \x01(\rR\tblockDimY\x12\x1e\n" +
	"\vblock_dim_z\x18\t \x01(\rR\tblockDimZ\x12(\n" +
	"\x10shared_mem_bytes\x18\n" +
	" \x01(\rR\x0esharedMemBytes\x12\x16\n" +
	"\x06stream\x18\v \x01(\x04R\x06stream\x12)\n" +
	"\x11device_pci_bus_id\x18\f \x01(\tR\x0edevicePciBusId\"}\n" +
	"\n" +
	"StatsEvent\x12%\n" +
	"\x0edropped_events\x18\x01 \x01(\x04R\rdroppedEvents\x12#\n" +
	"\rdropped_bytes\x18\x02 \x01(\x04R\fdroppedBytes\x12#\n" +
	"\rqueued_events\x18\x03 \x01(\x04R\fqueuedEventsB$Z\"sassguard/hookgo/protocol;protocolb\x06proto3"

var (
	file_proto_telemetry_proto_rawDescOnce sync.Once
	file_proto_telemetry_proto_rawDescData []byte
)

func file_proto_telemetry_proto_rawDescGZIP() []byte {
	file_proto_telemetry_proto_rawDescOnce.Do(func() {
		file_proto_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_telemetry_proto_rawDesc), len(file_proto_telemetry_proto_rawDesc)))
	})
	return file_proto_telemetry_proto_rawDescData
}

var file_proto_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_telemetry_proto_goTypes = []any{
	(*Envelope)(nil),          // 0: sassguard.telemetry.v1.Envelope
	(*ProcessInfoEvent)(nil),  // 1: sassguard.telemetry.v1.ProcessInfoEvent
	(*ClientHello)(nil),       // 2: sassguard.telemetry.v1.ClientHello
	(*CodeEvent)(nil),         // 3: sassguard.telemetry.v1.CodeEvent
	(*KernelLaunchEvent)(nil), // 4: sassguard.telemetry.v1.KernelLaunchEvent
	(*StatsEvent)(nil),        // 5: sassguard.telemetry.v1.StatsEvent
}
var file_proto_telemetry_proto_depIdxs = []int32{
	1, // 0: sassguard.telemetry.v1.Envelope.process_info:type_name -> sassguard.telemetry.v1.ProcessInfoEvent
	2, // 1: sassguard.telemetry.v1.Envelope.client_hello:type_name -> sassguard.telemetry.v1.ClientHello
	3, // 2: sassguard.telemetry.v1.Envelope.code:type_name -> sassguard.telemetry.v1.CodeEvent
	4, // 3: sassguard.telemetry.v1.Envelope.kernel_launch:type_name -> sassguard.telemetry.v1.KernelLaunchEvent
	5, // 4: sassguard.telemetry.v1.Envelope.stats:type_name -> sassguard.telemetry.v1.StatsEvent
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_telemetry_proto_init() }
func file_proto_telemetry_proto_init() {
	if File_proto_telemetry_proto != nil {
		return
	}
	file_proto_telemetry_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_ProcessInfo)(nil),
		(*Envelope_ClientHello)(nil),
		(*Envelope_Code)(nil),
		(*Envelope_KernelLaunch)(nil),
		(*Envelope_Stats)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_telemetry_proto_rawDesc), len(file_proto_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_telemetry_proto_goTypes,
		DependencyIndexes: file_proto_telemetry_proto_depIdxs,
		MessageInfos:      file_proto_telemetry_proto_msgTypes,
	}.Build()
	File_proto_telemetry_proto = out.File
	file_proto_telemetry_proto_goTypes = nil
	file_proto_telemetry_proto_depIdxs = nil
}
