#ifndef SASSGUARD_CONFIG_H
#define SASSGUARD_CONFIG_H

#define SASSGUARD_DEFAULT_SERVER_ADDR "127.0.0.1:59400"
#define SASSGUARD_DEFAULT_RING_CAPACITY 4096u
#define SASSGUARD_DEFAULT_DRAIN_BATCH_SIZE 128u
#define SASSGUARD_DEFAULT_RECONNECT_BACKOFF_MS 1000u
#define SASSGUARD_CAPTURE_DISABLE_ENV "SASSGUARD_CAPTURE_DISABLE"
#define SASSGUARD_HOOK_VERSION "0.1.0"

#endif  // SASSGUARD_CONFIG_H
